import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

import { unstable_ViewTransition as ViewTransition } from "react";

import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const quickSand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={quickSand.variable}>
        <ThemeProvider attribute="class" enableSystem disableTransitionOnChange>
          <ViewTransition>{children}</ViewTransition>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
